services:
  mt-login-db:
    image: 'postgres:latest'
    container_name: mt-login-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - mt-login-db-data:/var/lib/postgresql/data
    networks:
      - mt-login-net
  api-mt-login:
    container_name: ${API_CONTAINER_NAME}
    image: ${DOCKER_HUB_USER}/${API_CONTAINER_NAME}:${API_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_EXTERNAL_PORT}:${API_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - JWKS_URI=${JWKS_URI}
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - mt-login-net
    depends_on:
      - mt-login-db
    restart: always
networks:
  mt-login-net:
    driver: bridge
volumes:
  mt-login-db-data: