jwksUri: ${JWKS_URI:https://dev.login.mt.gov.br/auth/realms/mt-realm/protocol/openid-connect/certs}
# Se for uma lista de origens deve ser separado por virgula e sem espaço
# ex: allowedOrigins: https://www.sedec.mt.gov.br,https://www.gov.br/pt-br
allowedOrigins: ${CORS_ALLOWED_ORIGINS:*}
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mt_login_teste_db}
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
